// Sample data
const sampleData = [
	{
		id: "1",
		name: "John Doe",
		email: "john@example.com",
		role: "Admin",
		status: "Active",
	},
	{
		id: "2",
		name: "Jane Smith",
		email: "jane@example.com",
		role: "User",
		status: "Inactive",
	},
	{
		id: "3",
		name: "Bob Johnson",
		email: "bob@example.com",
		role: "Editor",
		status: "Active",
	},
	{
		id: "4",
		name: "Alice Brown",
		email: "alice@example.com",
		role: "User",
		status: "Active",
	},
	{
		id: "5",
		name: "Charlie Davis",
		email: "charlie@example.com",
		role: "Admin",
		status: "Active",
	},
	{
		id: "6",
		name: "Eva Wilson",
		email: "eva@example.com",
		role: "Editor",
		status: "Inactive",
	},
	{
		id: "7",
		name: "David Clark",
		email: "david@example.com",
		role: "User",
		status: "Active",
	},
	{
		id: "8",
		name: "Sophia White",
		email: "sophia@example.com",
		role: "Admin",
		status: "Inactive",
	},
	{
		id: "9",
		name: "Michael Lee",
		email: "michael@example.com",
		role: "Editor",
		status: "Active",
	},
	{
		id: "10",
		name: "Olivia Hall",
		email: "olivia@example.com",
		role: "User",
		status: "Inactive",
	},
	{
		id: "11",
		name: "Daniel Young",
		email: "daniel@example.com",
		role: "Admin",
		status: "Active",
	},
	{
		id: "12",
		name: "Emily Harris",
		email: "emily@example.com",
		role: "User",
		status: "Active",
	},
	{
		id: "13",
		name: "William Scott",
		email: "william@example.com",
		role: "Editor",
		status: "Inactive",
	},
	{
		id: "14",
		name: "Mia Turner",
		email: "mia@example.com",
		role: "Admin",
		status: "Active",
	},
	{
		id: "15",
		name: "James Walker",
		email: "james@example.com",
		role: "User",
		status: "Inactive",
	},
	{
		id: "16",
		name: "Isabella Lewis",
		email: "isabella@example.com",
		role: "Editor",
		status: "Active",
	},
	{
		id: "17",
		name: "Benjamin Allen",
		email: "benjamin@example.com",
		role: "Admin",
		status: "Active",
	},
	{
		id: "18",
		name: "Charlotte Wright",
		email: "charlotte@example.com",
		role: "User",
		status: "Inactive",
	},
	{
		id: "19",
		name: "Alexander King",
		email: "alexander@example.com",
		role: "Editor",
		status: "Active",
	},
	{
		id: "20",
		name: "Amelia Martinez",
		email: "amelia@example.com",
		role: "Admin",
		status: "Inactive",
	},
];

export default sampleData;
