import type { Metadata } from "next";
import RootProvider from "@/components/providers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import NodgeDynamicLayout from "@/components/shared/dynamic-layout";

import "./globals.css";

export const metadata: Metadata = {
	title: "NodeFlow",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={``}>
				<RootProvider>
					<NodgeDynamicLayout>
						{children}
					</NodgeDynamicLayout>
				</RootProvider>
				<SpeedInsights />
			</body>
		</html>
	);
}
